controllers/RentsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Rents;
use app\models\RentsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\Clients;
use yii\data\ActiveDataProvider;
use app\models\Scooters;
use app\models\RentPenalty;
use app\models\Penalty;
use yii\web\HttpException;

/**
 * RentsController implements the CRUD actions for Rents model.
 */
class RentsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                   [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /*public function actionData()
    {
        $week = \app\models\WeeklyCost::find()->where(['between', 'begin_time', 'end_time', '13:30:00'])->andWhere(['week_day' => 7])->one();
        echo "<pre>";
        print_r($week);
        echo "</pre>";
        $today = date("Y-m-d");
        $number = date('N', strtotime($today));
        echo "Today: " . $today . " weekday: " . $number . "<br>";

        $today = strtotime($today);
        $tomorrow = strtotime($today);
        $tomorrow = strtotime("+1 day", $today);
        $number2 = date('N', $tomorrow);
        echo "Tomorrow: " . date('Y-m-d', $tomorrow) . " weekday: " . $number2 . "<br>";
    }*/

    public function beforeAction($action)
    {
        if(Yii::$app->user->identity->id === null) return $this->redirect(['/site/login']);
        $permission = Yii::$app->user->identity->permission;

        if(($action->id =='list') && $permission == 'manager')
        {
            throw new HttpException(403,'У вас нет разрешения на доступ к этому действию.');
        }

        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * Lists all Rents models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $post = Yii::$app->request->post();
        $session = Yii::$app->session;
        $collapsed = ''; $button = 'minus';  $client = null; $client_status = 0;
        if($session['button'] == null | $session['button'] == 'plus') { $collapsed = 'collapsed-box'; $button = 'plus';}

        $model = new Rents();
        $model->begin_date = date('H:i d.m.Y');
        $model->tariff_id = 1;

        if(isset($post['phone'])){
            $client = Clients::find()->where(['like', 'phone', $post['phone']])->one();
            $model->client_id = $client->id;
            if($client !== null) {
                $rent = Rents::find()->where(['status' => 0, 'client_id' => $client->id])->one();
                if($rent !== null) $client_status = 1;
            }
        }

        if ($model->load($post) && $model->validate()) {
            
            $model->save();
            $model->setValues();
            Yii::$app->session->setFlash('success', "Успешно выполнено");
            return $this->redirect(['view', 'id' => $model->id]);
        }
        else {
            if(isset($model->client_id)){
                $client = Clients::find()->where(['id'=> $model->client_id])->one();
                $post['phone'] = $client->phone;                
            }
        }

        return $this->render('index', [
            'post' => $post,
            'client' => $client,
            'button' => $button,
            'collapsed' => $collapsed,
            'model' => $model,
            'client_status' => $client_status,
        ]);
    }

    public function actionScooterReturn($search)
    {    
        $request = Yii::$app->request;
        $penaltyProvider = null;

        $rent = Rents::find()->where(['scooter_id' => $search, 'status' => 0])->one();
        if($rent !== null){
            $query = RentPenalty::find()->where(['rent_id' => $rent->id]);
            $penaltyProvider = new ActiveDataProvider([
                'query' => $query,
            ]);                
        }

        if($request->post() && $rent->load($request->post()) && $rent->save()){
            $rent->saveValues();
            Yii::$app->session->setFlash('success', "Успешно завершено");
            return $this->redirect(['/rents/view', 'id' => $rent->id]);
        }

        return $this->render('scooter-return', [
            'post' => $request->post(),
            'rent' => $rent,
            'penaltyProvider' => $penaltyProvider,
        ]);
    }

    public function actionList()
    {
        $searchModel = new RentsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('list', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSearchScooter()
    {
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->post()){
                return $this->redirect(['scooter-return', 'search' => $request->post()['scooter']]);
            }else{           
                return [
                    'title'=> "Найти самоката",
                    'size' => 'normal',
                    'content'=>$this->renderAjax('search-scooter', []),
                    'footer'=>Html::button('Поиск',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }
        }       
    }

    /**
     * Displays a single Rents model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title'=> "Информация",
                'content'=>$this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
            ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Rents model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreatePenalty($id)
    {
        $request = Yii::$app->request;
        $model = new RentPenalty();
        $model->rent_id = $id;
        $model->cost = 0;

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                $rent = Rents::findOne($model->rent_id);
                $rent->penalty_sum += $model->cost;
                $rent->save();
                return [
                    'forceReload'=>'#scooter-pjax',
                    'title'=> "Штрафы",
                    'forceClose'=>true,
                    'content'=>'<span class="text-success">Успешно выполнено</span>',        
                ];         
            }else{           
                return [
                    'title'=> "Создать",
                    'size' => 'large',
                    'content'=>$this->renderAjax('create-penalty', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }       
    }

    /**
     * Delete an existing Rents model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDeletePenalty($id)
    {
        $request = Yii::$app->request;
        $penalty = RentPenalty::findOne($id);
        $rent = Rents::findOne($penalty->rent_id);
        $rent->penalty_sum -= $penalty->cost;
        $rent->save();
        $penalty->delete();
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#scooter-pjax'];
        }
    }

    /**
     * Finds the Rents model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Rents the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rents::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionScooterList($id)
    {
        $scooters = Scooters::find()->where(['station_id' => $id, 'status' => Scooters::STATUS_VACANT])->all();
        foreach ($scooters as $value) {
            echo "<option value = '".$value->id."'>".'Id = ' . $value->id. '; QR-код = '. $value->qr_code."</option>" ;
        }
    }

    public function actionPenaltyCost($id)
    {
        $penalty = Penalty::findOne($id);
        return $penalty->price;
    }

    public function actionChangeEndTime($trip_duration, $begin_date, $tariff_id)
    {
        if($trip_duration == null) return null;
        if($begin_date === null || $begin_date === '') $begin_date = date('Y-m-d H:i:s');

views/rents/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use app\models\Rents;

return [
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'id',
        'width' => '20px',
        'headerOptions'=>['class'=>'text-center'],
        'contentOptions'=>['class'=>'text-center'],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'client_id',
        'filter' => Rents::getClientsList(),
        'content' => function($data){
            return $data->client->surname . ' ' . $data->client->name . ' ' . $data->client->middle_name;
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'begin_date',
        'content' => function($data){
            if($data->begin_date != null) return date('H:i d.m.Y', strtotime($data->begin_date) );
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'end_date',
        'content' => function($data){
            if($data->end_date != null) return date('H:i d.m.Y', strtotime($data->end_date) );
        }
    ],
    /*[
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'trip_duration',
    ],*/
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'begin_station',
        'filter' => Rents::getStationsList(),
        'content' => function($data){
            return $data->beginStation->location;
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'scooter_id',
        'filter' => Rents::getScootersList(),
        'content' => function($data){
            return 'Id=' . $data->scooter->id . '; Qr-code='. $data->scooter->qr_code . ( $data->status == 0 ? '<a class="btn btn-primary btn-xs" data-pjax="0" title="Вернуть самокат" href="'. Url::toRoute(['/rents/scooter-return', 'search' => $data->scooter_id]).'"><i class="fa fa-reply-all"></i></a>' : '');
        }
    ],
    /*[
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'end_station',
        'filter' => Rents::getStationsList(),
        'content' => function($data){
            return $data->endStation->location;
        }
    ],*/
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'summa',
        'content' => function($data){
            return $data->summaDescription();
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'status',
        'filter' => Rents::getStatusList(),
        'content' => function($data){
            return $data->getStatusDescription();
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'payment_status',
        'width' => '150px;',
        'filter'=> [0 => 'Нет', 1 => 'Да'],
        'content' => function($data){
            if($data->payment_status == 1) return $data->getPaymentStatusDescription();
            else return Html::dropDownList(
                'data', 
                $data->payment_status, 
                $data->getPaymentStatusList(), 
                [
                    'class' =>'form-control',
                    'onchange'=>"$.get('/rents/edit-payment-status', {'id':$data->id, 'value':$(this).val()}, function(data){} ); ",
                ]
            );
        }
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'template' => '{view}',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title'=>'Просмотр','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Delete', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Are you sure?',
                          'data-confirm-message'=>'Are you sure want to delete this item'], 
    ],

];   

views/rents/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datetime\DateTimePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Rents */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rents-form padding_in_form">

    <?php $form = ActiveForm::begin(['id' => 'rent-form', 'options' => ['method' => 'post',  'autocomplete'=>"off"]]); ?>

    <div class="row">
        <div class="col-md-3">
            <?= $form->field($model, 'begin_station')->dropDownList(
                $model->getStationsList(),
                [
                    'prompt' => 'Выберите',
                    'onchange' => '
                        $.post( "/rents/scooter-list?id="+$(this).val(), function( data ){
                            $( "#scooter_id" ).html( data);
                        });
                    ',
                ]
            ) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'scooter_id')->dropDownList($model->getScootersList($model->begin_station),[ 'id' => 'scooter_id', 'prompt' => 'Выберите']) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'tariff_id')->dropDownList($model->getTariffList(),
            [ 
                'id' => 'tariff_id', 
                /*'prompt' => 'Выберите'*/
                'onchange' => '
                    $.post( "/rents/change-end-time?trip_duration=" + $("#trip_duration").val() + "&begin_date=" + $("#rents-begin_date").val() + "&tariff_id=" + $("#tariff_id").val(), function( data ){
                        //alert(data);
                        $( "#end_date" ).val( data);
                    });
                ',
            ]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'promo_code')->textInput([]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <?= $form->field($model, 'payment_status')->dropDownList($model->getPaymentStatusList(),
            [ 
                'prompt' => 'Выберите'
            ]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'trip_duration')->textInput([
                'type' => 'number',
                'id' => 'trip_duration',
                'onchange' => '
                    $.post( "/rents/change-end-time?trip_duration=" + $("#trip_duration").val() + "&begin_date=" + $("#rents-begin_date").val() + "&tariff_id=" + $("#tariff_id").val(), function( data ){
                        //alert(data);
                        $( "#end_date" ).val( data);
                    });
                ',
            ]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model,"begin_date", [])->widget(
                    \yii\widgets\MaskedInput::class, [
                        'mask' => "h:s 1.2.y",
                        'clientOptions' => [
                            'alias' => 'datetime',
                            "placeholder" => "чч:мм дд.мм.гггг",
                            "separator" => "."
                        ],
                        'options' => [
                            'onchange'=>'function(e) { 
                                $.post( "/rents/change-end-time?trip_duration=" + $("#trip_duration").val() + "&begin_date=" + $("#rents-begin_date").val() + "&tariff_id=" + $("#tariff_id").val(), function( data ){
                                    var h = $("#trip_duration").val()  + $("#rents-begin_date").val() + $("#tariff_id").val();
                                    //alert(h);
                                    $( "#end_date" ).val( data);
                                });
                            }'
                        ]
                    ]
                );
            ?>
            <?php /*$form->field($model, 'begin_date')->widget(DateTimePicker::classname(), [
                'options' => ['placeholder' => 'Выберите ...'],
                'pluginEvents' => [
                    "changeDate" => 'function(e) { 
                        $.post( "/rents/change-end-time?trip_duration=" + $("#trip_duration").val() + "&begin_date=" + $("#rents-begin_date").val() + "&tariff_id=" + $("#tariff_id").val(), function( data ){
                            var h = $("#trip_duration").val()  + $("#rents-begin_date").val() + $("#tariff_id").val();
                            //alert(h);
                            $( "#end_date" ).val( data);
                        });
                    }',
                ],
                'type' => DateTimePicker::TYPE_COMPONENT_APPEND,
                'removeButton' => false,
                'pluginOptions' => [
                    'format' => 'hh:ii dd.mm.yyyy',
                    'autoclose' => true
                ]
            ]);*/ ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'end_date')->textInput(['disabled' =>true, 'id' => 'end_date']) ?>
        </div>
    </div>

    <?= $form->field($model, 'client_id')->hiddenInput()->label(false) ?>
  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton('Сдать самокат', ['class' => 'btn btn-success']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/rents/_form2.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datetime\DateTimePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Rents */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rents-form padding_in_form">

    <?php $form = ActiveForm::begin(['id' => 'rent-form', 'options' => ['method' => 'post']]); ?>

    <div class="row">
        <div class="col-md-3">
            <?= $form->field($model, 'end_station')->dropDownList(
                $model->getStationsList(),
                [
                    /*'prompt' => 'Выберите',*/
                ]
            ) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'summa')->textInput(['type' => 'number', 'value' => $model->summaDescription()]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'penalty_sum')->textInput(['type' => 'number']) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'run_length')->textInput(['type' => 'number']) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'end_date')->textInput(['disabled' =>true, 'id' => 'end_date']) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'comment')->textarea(['rows' => 2]) ?>
        </div>
    </div>
  
	<div class="form-group">
	    <?= Html::submitButton('Завершить поездку', ['class' => 'btn btn-success']) ?>
	</div>

    <?php ActiveForm::end(); ?>
    
</div>

views/rents/_search.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<div class="client-form">
    <div class="box-body">
        <?php $form = ActiveForm::begin(['id' => 'search-form', 'options' => ['method' => 'post',]]); ?>
            <div class="row">
                <div class="col-md-4" >
                <label>Телефон номер клиента</label> 
                    <?=\yii\widgets\MaskedInput::widget([
                        'name' => 'phone',
                        'value' => $post['phone'],
                        'mask' => '+7(999)999-99-99',
                        'options' => ['class'=>'form-control',]
                    ])?>
                </div>  
                <div class="col-md-6">
                </div>
                <div class="form-group pull-right" >
                    <?= Html::submitButton('Найти клиента', ['class' => 'btn btn-info', 'style' => 'margin-top:25px;']) ?>        
                </div>
            </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/rents/client.php
<?php

use yii\helpers\Html;

if (!file_exists('uploads/clients/' . $model->passport_photo) || $model->passport_photo == '') {
    $path = 'http://' . $_SERVER['SERVER_NAME'].'/images/no-image.jpg';
} else {
    $path = 'http://' . $_SERVER['SERVER_NAME'].'/uploads/clients/' . $model->passport_photo;
}

?>

<table class="kv-grid-table table table-bordered table-striped table-condensed">
	<thead>
		<tr>
			<th class="kv-align-center kv-align-middle" style="width: 2.35%;" data-col-seq="0">ID</th>
			<th data-col-seq="1" style="width: 10.95%;">Фото паспорта</th>
			<th data-col-seq="2" style="width: 12.41%;">Фамилия</th>
			<th data-col-seq="3" style="width: 10.21%;">Имя</th>
			<th data-col-seq="4" style="width: 11.58%;">Отчество</th>
			<th data-col-seq="5" style="width: 12.06%;">Телефон</th>
			<th data-col-seq="6" style="width: 15.34%;">Дата рождения</th>
			<th data-col-seq="7" style="width: 12.65%;">Статус</th>
			<th data-col-seq="8" style="width: 15.65%;">Паспорт</th>
			<th class="kv-align-center kv-align-middle skip-export" style="width: 5.41%;" data-col-seq="8">Просмотр</th>
		</tr>
	</thead>
	<tbody>
		<tr data-key="1">
			<td class="kv-align-center kv-align-middle" style="width:30px;" data-col-seq="0">1</td>
			<td data-col-seq="1"><?=Html::img($path, [ 'style' => 'width:70px;height:50px;'])?></td>
			<td data-col-seq="2"><?=$model->surname?></td>
			<td data-col-seq="3"><?=$model->name?></td>
			<td data-col-seq="4"><?=$model->middle_name?></td>
			<td data-col-seq="5"><?=$model->phone?></td>
			<td data-col-seq="6"><?=$model->birthday?></td>
			<td data-col-seq="7"><?=$model->getStatusDescription()?></td>
			<td data-col-seq="8"><?=$model->getPassportDescription()?></td>
			<td class="skip-export kv-align-center kv-align-middle" style="width:50px;" data-col-seq="8">
				<a href="/clients/view-cart?id=<?=$model->id?>" title="Просмотр" aria-label="Просмотр" role="modal-remote" data-toggle="tooltip">
					<span class="glyphicon glyphicon-eye-open"></span>
				</a>
			</td>
		</tr>
	</tbody>
</table>

views/rents/create-penalty.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<div class="rents-form padding_in_form">
    <?php $form = ActiveForm::begin(['id' => 'penalty-form', 'options' => ['method' => 'post']]); ?>
        <div class="row">
            <div class="col-md-9">
                <?= $form->field($model, 'penalty_id')->dropDownList(
                    $model->getPenaltyList(),
                    [
                        //'prompt' => 'Выберите',
                        'onchange' => '
                            $.post( "/rents/penalty-cost?id="+$(this).val(), function( data ){
                                $( "#price" ).val( data);
                            });
                        ',
                    ]
                ) ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'cost')->textInput([ 'type' => 'number', 'id' => 'price']) ?>
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div>

views/rents/list.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ClientsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Дашбоард';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="clients-index">
    <div id="ajaxCrudDatatable">
        <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'responsiveWrap' => false,
            'columns' => require(__DIR__.'/_columns.php'),
            'toolbar'=> [
                ['content'=>
                    '{export}'.
                    '{toggleData}'
                ],
            ],          
            'striped' => true,
            'condensed' => true,
            'responsive' => true,          
            'panel' => [
                'type' => 'primary', 
                'heading' => '<i class="glyphicon glyphicon-list"></i> Поездки',
                'after'=>'',
            ]
        ])?>
    </div>
</div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/rents/penalties.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use app\models\Penalty;
use johnitvn\ajaxcrud\CrudAsset;
use yii\bootstrap\Modal;

CrudAsset::register($this);

?>
<?=GridView::widget([
    'id'=>'penalty-table',
    'dataProvider' => $penaltyProvider,
    'pjax'=>true,
    'responsiveWrap' => false,
    'columns' => [
        [
            'class' => 'kartik\grid\SerialColumn',
            'width' => '30px',
        ],

        /*[
            'class'=>'\kartik\grid\DataColumn',
            'attribute'=>'rent_id',
            'content' => function($data){
                return ;
            }
        ],*/
        [
            'class'=>'\kartik\grid\DataColumn',
            'attribute'=>'penalty_id',
            'filter' => ArrayHelper::map(Penalty::find()->all(),'id', 'category'),
            'content' => function($data){
                return $data->getPenaltyList()[$data->penalty_id];
            }
        ],
        [
            'class'=>'\kartik\grid\DataColumn',
            'attribute'=>'cost',
        ],
        [ 
            'class' => 'kartik\grid\ActionColumn',
            'dropdown' => false,
            'template' => '{delete}',
            'vAlign'=>'middle',
            'header' => 'Удалить',
            'buttons'  => [
                'delete' => function ($url, $model) {
                    if($model->rent->status == 0){
                        $url = Url::to(['/rents/delete-penalty', 'id' => $model->id]);
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                            'role'=>'modal-remote','title'=>'Удалить', 
                            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                            'data-request-method'=>'post',
                            'data-toggle'=>'tooltip',
                            'data-confirm-title'=>'Подтвердите действие',
                            'data-confirm-message'=>'Вы уверены что хотите удалить этого элемента?'
                        ]);
                    }
                },
            ],
        ],
    ],
    'toolbar'=> [
        ['content'=>
            $rent->status == 0 ? Html::a('Добавить <i class="glyphicon glyphicon-plus"></i>', ['/rents/create-penalty', 'id' => $rent->id], ['role'=>'modal-remote','title'=> 'Создать','class'=>'btn btn-primary']) : ''
        ],
    ],          
    'striped' => true,
    'condensed' => true,
    'responsive' => true,          
    'panel' => [
        'type' => 'primary', 
        'heading' => '<i class="glyphicon glyphicon-list"></i> Список штрафов',
        'after'=>'',
    ]
])?>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/rents/search-scooter.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<div class="padding_in_form">
    <?php $form = ActiveForm::begin(['id' => 'search-form', 'options' => ['method' => 'post',]]); ?>
        <div class="row">
            <div class="col-md-12">
                <label>ID самоката</label> 
                <input type="number" class="form-control" required="" name="scooter">
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div>